import {onetomany} from 'nodedata/core/decorators';
import {Strict} from 'nodedata/mongoose/enums';
import {field, document} from 'nodedata/mongoose/decorators';
import {User} from 'nodedata/security/auth/user';
import {Roles1} from './RoleModel';
import {Types} from 'mongoose';

@document({ name: 'rsUserModel', strict: Strict.false })
export class RSUserModel {
    @field({ primary: true, autogenerated: true })
    _id: Types.ObjectId;

    @field()
    name: string;

    @field()
    password: string;

    @field()
    email: string;

    @onetomany({ rel: 'roles', itemType: Roles1, embedded: true, persist: true, eagerLoading: false })
    roles: Array<Roles1>;

    constructor(name: string, password: string, email: string, roles: Array<Roles1>) {
        this.name = name;
        this.password = password;
        this.email = email;
        this.roles = roles;
    }
}

export default RSUserModel;